# Generated by Django 5.1.1 on 2024-10-20 15:22


from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE habits_habit
            ALTER COLUMN time_to_complete
            TYPE integer USING EXTRACT(EPOCH FROM time_to_complete)::integer;
            """,
        ),
    ]
