# Generated by Django 5.1.1 on 2024-10-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_periodicity_alter_habit_time_to_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='periodicity',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time_to_complete',
        ),
        migrations.AddField(
            model_name='habit',
            name='period',
            field=models.PositiveIntegerField(default=1, verbose_name='переодичность'),
        ),
        migrations.AddField(
            model_name='habit',
            name='time_complete',
            field=models.PositiveIntegerField(default=0, verbose_name='время на выполнение'),
        ),
    ]
