# Generated by Django 5.1.1 on 2024-10-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_periodicity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='time_complete',
            new_name='time_to_complete',
        ),
    ]
